version: '3'
services:
  db:
    container_name: 'pag_tasks'
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: tasks
    ports:
      - 5433:5432
# postgres adminer
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:2.204.4-alpine
    restart: always
    ports:
      - 8081:8080
      - 5000:5000
      - 50000:50000
    volumes:
      - ./jenkins_host:/var/jenkins_home
    tty: true
